[project]
name = "taxgenius"
version = "0.1.0"
description = "A synthetic data generation framework for evaluating LLM reasoning on German tax law."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "groq>=0.31.1",
    "pyyaml>=6.0.2",
]
